# The id and meta of the item:
id: "shulker_shell"

# Message position (popup, tip or title):
message-position: "popup"

# Messages:
 # {chestCount} to indicate the number of vaults around the player.
 # {chestDistance} to indicate the distance between player and the chest.
 # {lineBreak} to make a line break.
no-chest: "§cNo chest around you"
chest-detected: "§aThere are {chestCount} chest(s) near you...{lineBreak}The closest chest near you is at {chestDistance} blocks !"

# The radius of detection:
radius: 70

# Avaible: chest, trapped_chest, ender_chest, hopper, barrel, shulker,
detection:
  - "chest"
  - "trapped_chest"
  - "ender_chest"
  
# The time between each search in seconds (the lower it is, the more risk there is of lag; Recommanded: 3):
repeat: 1

# Plugin's version, please don't touch it !
version: "2.1.0"
